---
#- name: Check for updates, download & install

- name: Add sudo users
  user:
    name: "{{ item.name }}"
    create_home: yes
    shell: /bin/bash
    state: present
  with_items: "{{ sudoers }}"

#- name: Add non-sudo users
#  user:
#    name: "{{ item.name }}"
#    create_home: yes
#    shell: /bin/bash
#    state: present
#  with_items: "{{ users }}"

#- name: Add deploy keys for users
#  authorized_key:
#    user: {{ item.name }}
#    key: "{{ lookup('file', 'keys/{{ item.name }}') }}"
#    state: present
#  with_items: "{{ users }}"